# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'JPSThumbnailAnnotation' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JPSThumbnailAnnotation
  pod 'JPSThumbnailAnnotation', :path => '../'

end